[package]
name = "bevy_mod_index"
version = "0.1.0"
edition = "2021"
license = "MIT"

[profile.dev.package."*"]
opt-level = 3

[dependencies.bevy]
default_features = false
git = "https://github.com/chrisjuchem/bevy-fork"
branch = "main"

# Dependencies for examples
[dev-dependencies]
rand = "0.8.5"

[dev-dependencies.bevy]
git = "https://github.com/chrisjuchem/bevy-fork"
branch = "main"
features = ["dynamic_linking"]
